/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackComponent: typeof import('./src/components/backComponent.vue')['default']
    ChapterComponent: typeof import('./src/components/chapterComponent.vue')['default']
    ComicItemComponent: typeof import('./src/components/comicItemComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanSlider: typeof import('vant/es')['Slider']
  }
}
